#!/bin/bash

########## USAGE ########
# ./sbtd <sbt commands> #
#                       #
# See docker-usage.md   #
#########################

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

IMAGE="1science/sbt:0.13-oracle-jdk-8"

docker run --rm -it \
    -v ${DIR}:/app \
    --name sbtd \
    ${IMAGE} sbt -sbt-dir /app/.sbt -ivy /app/.ivy "$@"
